# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text_capture.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import cv2
import pytesseract
from googletrans import Translator
from PIL import ImageGrab, Image
import numpy as np


def translate_from_clipboard():
    pytesseract.pytesseract.tesseract_cmd = r'D:\Program Files (x86)\Tesseract-OCR\tesseract.exe'
    img = ImageGrab.grabclipboard()
    img = np.array(img)

    try:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        text = pytesseract.image_to_string(img)
        # Detects the text's language using Google API
        translator = Translator()
        translator.detect(text)
        ui.captured_text.setText(text)
        result = translator.translate(text, dest='pl')
        ui.translated_text.setText(result.text)
        print(result.text)
    except (TypeError, AttributeError):
        print("No image in clipboard/Google services unaviable")


def translate_from_file():
    pytesseract.pytesseract.tesseract_cmd = r'D:\Program Files (x86)\Tesseract-OCR\tesseract.exe'
    filename = QtWidgets.QFileDialog.getOpenFileName(None, 'Open File')
    print(filename[0])
    img = Image.open(filename[0])
    img = np.array(img)

    try:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        text = pytesseract.image_to_string(img)
        # Detects the text's language using Google API
        translator = Translator()
        translator.detect(text)
        ui.captured_text.setText(text)
        result = translator.translate(text, dest='pl')
        ui.translated_text.setText(result.text)
        print(result.text)
    except (TypeError, AttributeError):
        print("No image in clipboard")

class Ui_TextCapture(object):
    def setupUi(self, TextCapture):
        TextCapture.setObjectName("TextCapture")
        TextCapture.resize(480, 640)

        self.centralwidget = QtWidgets.QWidget(TextCapture)
        self.centralwidget.setObjectName("centralwidget")

        self.paste_clipboard = QtWidgets.QPushButton(self.centralwidget)
        self.paste_clipboard.setGeometry(QtCore.QRect(70, 30, 331, 31))
        self.paste_clipboard.setObjectName("paste_clipboard")

        self.paste_img = QtWidgets.QPushButton(self.centralwidget)
        self.paste_img.setGeometry(QtCore.QRect(70, 70, 331, 31))
        self.paste_img.setObjectName("paste_img")

        self.captured_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.captured_text.setGeometry(QtCore.QRect(40, 200, 391, 181))
        self.captured_text.setObjectName("captured_text")

        self.translated_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.translated_text.setGeometry(QtCore.QRect(40, 420, 391, 181))
        self.translated_text.setObjectName("translated_text")

        self.captured_text_label = QtWidgets.QLabel(self.centralwidget)
        self.captured_text_label.setGeometry(QtCore.QRect(40, 170, 391, 31))
        self.captured_text_label.setObjectName("captured_text_label")

        self.translated_text_label = QtWidgets.QLabel(self.centralwidget)
        self.translated_text_label.setGeometry(QtCore.QRect(40, 390, 391, 31))
        self.translated_text_label.setObjectName("translated_text_label")

        TextCapture.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TextCapture)
        self.statusbar.setObjectName("statusbar")
        TextCapture.setStatusBar(self.statusbar)

        self.retranslateUi(TextCapture)
        QtCore.QMetaObject.connectSlotsByName(TextCapture)

    def retranslateUi(self, TextCapture):
        _translate = QtCore.QCoreApplication.translate
        TextCapture.setWindowTitle(_translate("TextCapture", "TextCapture"))
        self.paste_clipboard.setText(_translate("TextCapture", "Paste image from clipboard"))
        self.paste_img.setText(_translate("TextCapture", "Search for image on your disc"))
        self.captured_text_label.setText(_translate("TextCapture", "Captured text:"))
        self.translated_text_label.setText(_translate("TextCapture", "Translated text:"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TextCapture = QtWidgets.QMainWindow()
    ui = Ui_TextCapture()
    ui.setupUi(TextCapture)
    TextCapture.show()

    ui.paste_clipboard.pressed.connect(lambda: translate_from_clipboard())
    ui.paste_img.pressed.connect(lambda: translate_from_file())
    
    sys.exit(app.exec_())
